"""
Seed sample Lead data for IB Commerce module
"""
import asyncio
import os
from motor.motor_asyncio import AsyncIOMotorClient
from datetime import datetime, timezone
import uuid

# MongoDB connection
mongo_url = os.environ.get('MONGO_URL')
client = AsyncIOMotorClient(mongo_url)
db = client[os.environ.get('DB_NAME', 'innovate_books')]

# Sample lead data
sample_leads = [
    {
        "id": str(uuid.uuid4()),
        "lead_id": "LEAD-2025-001",
        "lead_status": "Captured",
        "lead_source": "Website",
        "capture_channel": "Google Ads",
        "captured_by": "demo_user",
        "capture_date": datetime.now(timezone.utc),
        "linked_sop_version": "v1.0",
        "business_name": "TechVision Solutions Pvt Ltd",
        "trade_name": "TechVision",
        "industry_type": "Technology",
        "business_size": "Mid",
        "business_model": "B2B",
        "number_of_employees": 150,
        "annual_revenue": 50000000.0,
        "tax_registration_number": "29AABCT1234E1Z5",
        "business_registration_id": "U72900MH2020PTC123456",
        "website_url": "https://techvision.com",
        "primary_contact_name": "Rajesh Kumar",
        "primary_email": "rajesh@techvision.com",
        "primary_phone": "+91 9876543210",
        "designation": "Chief Technology Officer",
        "office_address": "Tower A, Cyber City",
        "city": "Bangalore",
        "state": "Karnataka",
        "country": "India",
        "postal_code": "560001",
        "kyc_status": "Verified",
        "kyc_documents": [],
        "blacklist_flag": False,
        "compliance_score": 85.0,
        "risk_category": "Low",
        "verification_date": None,
        "verified_by": None,
        "credit_score_internal": 78.0,
        "credit_score_external": 750.0,
        "credit_grade": "B",
        "credit_limit_proposed": 10000000.0,
        "payment_terms_proposed": "Net 30",
        "past_defaults_flag": False,
        "financial_health_index": 82.0,
        "lead_score": 75.0,
        "qualification_criteria": "High revenue, strong credit",
        "decision_maker_identified": True,
        "expected_deal_value": 8000000.0,
        "potential_product_line": "Enterprise Software Solutions",
        "timeline_to_close": 45,
        "lead_priority": "High",
        "approval_status": "Pending",
        "approved_by": None,
        "approval_date": None,
        "approval_remarks": None,
        "sop_run_ids": [str(uuid.uuid4())],
        "customer_id": None,
        "conversion_date": None,
        "conversion_remarks": None,
        "created_at": datetime.now(timezone.utc),
        "updated_at": datetime.now(timezone.utc)
    },
    {
        "id": str(uuid.uuid4()),
        "lead_id": "LEAD-2025-002",
        "lead_status": "Validated",
        "lead_source": "Referral",
        "capture_channel": "Partner Network",
        "captured_by": "demo_user",
        "capture_date": datetime.now(timezone.utc),
        "linked_sop_version": "v1.0",
        "business_name": "Global Manufacturing Co",
        "trade_name": "GMC",
        "industry_type": "Manufacturing",
        "business_size": "Enterprise",
        "business_model": "B2B",
        "number_of_employees": 500,
        "annual_revenue": 200000000.0,
        "tax_registration_number": "27AABCG5678F1Z1",
        "business_registration_id": "U28100MH2015PLC456789",
        "website_url": "https://globalmfg.com",
        "primary_contact_name": "Priya Sharma",
        "primary_email": "priya@globalmfg.com",
        "primary_phone": "+91 9988776655",
        "designation": "VP Operations",
        "office_address": "Industrial Area Phase 2",
        "city": "Pune",
        "state": "Maharashtra",
        "country": "India",
        "postal_code": "411001",
        "kyc_status": "Verified",
        "kyc_documents": [],
        "blacklist_flag": False,
        "compliance_score": 92.0,
        "risk_category": "Low",
        "verification_date": datetime.now(timezone.utc),
        "verified_by": "demo_user",
        "credit_score_internal": 88.0,
        "credit_score_external": 810.0,
        "credit_grade": "A",
        "credit_limit_proposed": 30000000.0,
        "payment_terms_proposed": "Net 45",
        "past_defaults_flag": False,
        "financial_health_index": 90.0,
        "lead_score": 88.0,
        "qualification_criteria": "Enterprise client, excellent credit",
        "decision_maker_identified": True,
        "expected_deal_value": 25000000.0,
        "potential_product_line": "Supply Chain Management Software",
        "timeline_to_close": 60,
        "lead_priority": "High",
        "approval_status": "Approved",
        "approved_by": "demo_user",
        "approval_date": datetime.now(timezone.utc),
        "approval_remarks": "Excellent prospect",
        "sop_run_ids": [str(uuid.uuid4())],
        "customer_id": None,
        "conversion_date": None,
        "conversion_remarks": None,
        "created_at": datetime.now(timezone.utc),
        "updated_at": datetime.now(timezone.utc)
    },
    {
        "id": str(uuid.uuid4()),
        "lead_id": "LEAD-2025-003",
        "lead_status": "Qualified",
        "lead_source": "LinkedIn",
        "capture_channel": "Organic Social",
        "captured_by": "demo_user",
        "capture_date": datetime.now(timezone.utc),
        "linked_sop_version": "v1.0",
        "business_name": "HealthCare Plus Services",
        "trade_name": "HC Plus",
        "industry_type": "Healthcare",
        "business_size": "SME",
        "business_model": "B2C",
        "number_of_employees": 80,
        "annual_revenue": 30000000.0,
        "tax_registration_number": "29AABCH7890G1Z2",
        "business_registration_id": "U85100KA2018PTC789012",
        "website_url": "https://hcplus.com",
        "primary_contact_name": "Dr. Amit Patel",
        "primary_email": "amit@hcplus.com",
        "primary_phone": "+91 8877665544",
        "designation": "Managing Director",
        "office_address": "MG Road Medical Complex",
        "city": "Kochi",
        "state": "Kerala",
        "country": "India",
        "postal_code": "682001",
        "kyc_status": "Pending",
        "kyc_documents": [],
        "blacklist_flag": False,
        "compliance_score": 72.0,
        "risk_category": "Medium",
        "verification_date": None,
        "verified_by": None,
        "credit_score_internal": 65.0,
        "credit_score_external": 680.0,
        "credit_grade": "C",
        "credit_limit_proposed": 5000000.0,
        "payment_terms_proposed": "Net 30",
        "past_defaults_flag": False,
        "financial_health_index": 70.0,
        "lead_score": 62.0,
        "qualification_criteria": "Growing healthcare sector",
        "decision_maker_identified": True,
        "expected_deal_value": 4500000.0,
        "potential_product_line": "Hospital Management System",
        "timeline_to_close": 90,
        "lead_priority": "Medium",
        "approval_status": "Pending",
        "approved_by": None,
        "approval_date": None,
        "approval_remarks": None,
        "sop_run_ids": [str(uuid.uuid4())],
        "customer_id": None,
        "conversion_date": None,
        "conversion_remarks": None,
        "created_at": datetime.now(timezone.utc),
        "updated_at": datetime.now(timezone.utc)
    },
    {
        "id": str(uuid.uuid4()),
        "lead_id": "LEAD-2025-004",
        "lead_status": "Approved",
        "lead_source": "Trade Show",
        "capture_channel": "Industry Conference",
        "captured_by": "demo_user",
        "capture_date": datetime.now(timezone.utc),
        "linked_sop_version": "v1.0",
        "business_name": "Retail King Enterprises",
        "trade_name": "Retail King",
        "industry_type": "Retail",
        "business_size": "Mid",
        "business_model": "Hybrid",
        "number_of_employees": 250,
        "annual_revenue": 75000000.0,
        "tax_registration_number": "09AABCR3456H1Z3",
        "business_registration_id": "U52100DL2019PTC234567",
        "website_url": "https://retailking.com",
        "primary_contact_name": "Suresh Reddy",
        "primary_email": "suresh@retailking.com",
        "primary_phone": "+91 7766554433",
        "designation": "CEO",
        "office_address": "Connaught Place",
        "city": "New Delhi",
        "state": "Delhi",
        "country": "India",
        "postal_code": "110001",
        "kyc_status": "Verified",
        "kyc_documents": [],
        "blacklist_flag": False,
        "compliance_score": 80.0,
        "risk_category": "Low",
        "verification_date": datetime.now(timezone.utc),
        "verified_by": "demo_user",
        "credit_score_internal": 82.0,
        "credit_score_external": 780.0,
        "credit_grade": "B",
        "credit_limit_proposed": 15000000.0,
        "payment_terms_proposed": "Net 30",
        "past_defaults_flag": False,
        "financial_health_index": 85.0,
        "lead_score": 80.0,
        "qualification_criteria": "Established retail chain",
        "decision_maker_identified": True,
        "expected_deal_value": 12000000.0,
        "potential_product_line": "Omnichannel Retail Platform",
        "timeline_to_close": 30,
        "lead_priority": "High",
        "approval_status": "Approved",
        "approved_by": "demo_user",
        "approval_date": datetime.now(timezone.utc),
        "approval_remarks": "Ready for conversion",
        "sop_run_ids": [str(uuid.uuid4())],
        "customer_id": None,
        "conversion_date": None,
        "conversion_remarks": None,
        "created_at": datetime.now(timezone.utc),
        "updated_at": datetime.now(timezone.utc)
    },
    {
        "id": str(uuid.uuid4()),
        "lead_id": "LEAD-2025-005",
        "lead_status": "Converted",
        "lead_source": "Email",
        "capture_channel": "Cold Outreach",
        "captured_by": "demo_user",
        "capture_date": datetime.now(timezone.utc),
        "linked_sop_version": "v1.0",
        "business_name": "FinConsult Advisory LLP",
        "trade_name": "FinConsult",
        "industry_type": "Finance",
        "business_size": "SME",
        "business_model": "B2B",
        "number_of_employees": 45,
        "annual_revenue": 20000000.0,
        "tax_registration_number": "27AABCF2345I1Z4",
        "business_registration_id": "AAL-1234",
        "website_url": "https://finconsult.com",
        "primary_contact_name": "Meera Iyer",
        "primary_email": "meera@finconsult.com",
        "primary_phone": "+91 6655443322",
        "designation": "Partner",
        "office_address": "Nariman Point",
        "city": "Mumbai",
        "state": "Maharashtra",
        "country": "India",
        "postal_code": "400021",
        "kyc_status": "Verified",
        "kyc_documents": [],
        "blacklist_flag": False,
        "compliance_score": 95.0,
        "risk_category": "Low",
        "verification_date": datetime.now(timezone.utc),
        "verified_by": "demo_user",
        "credit_score_internal": 90.0,
        "credit_score_external": 820.0,
        "credit_grade": "A",
        "credit_limit_proposed": 8000000.0,
        "payment_terms_proposed": "Net 30",
        "past_defaults_flag": False,
        "financial_health_index": 92.0,
        "lead_score": 92.0,
        "qualification_criteria": "Financial services expertise",
        "decision_maker_identified": True,
        "expected_deal_value": 6000000.0,
        "potential_product_line": "Financial Analytics Platform",
        "timeline_to_close": 30,
        "lead_priority": "High",
        "approval_status": "Approved",
        "approved_by": "demo_user",
        "approval_date": datetime.now(timezone.utc),
        "approval_remarks": "Converted to customer",
        "sop_run_ids": [str(uuid.uuid4())],
        "customer_id": str(uuid.uuid4()),
        "conversion_date": datetime.now(timezone.utc),
        "conversion_remarks": "Successfully onboarded",
        "created_at": datetime.now(timezone.utc),
        "updated_at": datetime.now(timezone.utc)
    },
    {
        "id": str(uuid.uuid4()),
        "lead_id": "LEAD-2025-006",
        "lead_status": "Rejected",
        "lead_source": "Website",
        "capture_channel": "Contact Form",
        "captured_by": "demo_user",
        "capture_date": datetime.now(timezone.utc),
        "linked_sop_version": "v1.0",
        "business_name": "Small Ventures Pvt Ltd",
        "trade_name": "SmallV",
        "industry_type": "Consulting",
        "business_size": "SME",
        "business_model": "B2B",
        "number_of_employees": 12,
        "annual_revenue": 5000000.0,
        "tax_registration_number": "29AABCS1234J1Z5",
        "business_registration_id": "U74900KA2021PTC345678",
        "website_url": "https://smallventures.com",
        "primary_contact_name": "Anil Gupta",
        "primary_email": "anil@smallventures.com",
        "primary_phone": "+91 5544332211",
        "designation": "Founder",
        "office_address": "Koramangala",
        "city": "Bangalore",
        "state": "Karnataka",
        "country": "India",
        "postal_code": "560034",
        "kyc_status": "Rejected",
        "kyc_documents": [],
        "blacklist_flag": True,
        "compliance_score": 35.0,
        "risk_category": "High",
        "verification_date": datetime.now(timezone.utc),
        "verified_by": "demo_user",
        "credit_score_internal": 40.0,
        "credit_score_external": 520.0,
        "credit_grade": "D",
        "credit_limit_proposed": 0.0,
        "payment_terms_proposed": "N/A",
        "past_defaults_flag": True,
        "financial_health_index": 30.0,
        "lead_score": 25.0,
        "qualification_criteria": "Below threshold",
        "decision_maker_identified": False,
        "expected_deal_value": 500000.0,
        "potential_product_line": "Basic Consulting Tools",
        "timeline_to_close": 0,
        "lead_priority": "Low",
        "approval_status": "Rejected",
        "approved_by": "demo_user",
        "approval_date": datetime.now(timezone.utc),
        "approval_remarks": "Failed compliance check - past defaults",
        "sop_run_ids": [str(uuid.uuid4())],
        "customer_id": None,
        "conversion_date": None,
        "conversion_remarks": None,
        "created_at": datetime.now(timezone.utc),
        "updated_at": datetime.now(timezone.utc)
    }
]

async def seed_leads():
    try:
        # Clear existing leads
        result = await db.commerce_leads.delete_many({})
        print(f"Cleared {result.deleted_count} existing leads")
        
        # Insert sample leads
        result = await db.commerce_leads.insert_many(sample_leads)
        print(f"✅ Successfully seeded {len(result.inserted_ids)} sample leads")
        
        # Verify
        count = await db.commerce_leads.count_documents({})
        print(f"Total leads in database: {count}")
        
        # Show summary
        print("\nSeeded Leads Summary:")
        for lead in sample_leads:
            print(f"  - {lead['lead_id']}: {lead['business_name']} ({lead['lead_status']})")
        
    except Exception as e:
        print(f"❌ Error seeding leads: {str(e)}")
    finally:
        client.close()

if __name__ == "__main__":
    asyncio.run(seed_leads())
