"""
Extended Seed Data for Manufacturing Lead Module
Creates 15+ records for each master type
"""

import asyncio
import os
from datetime import datetime, timedelta
from motor.motor_asyncio import AsyncIOMotorClient

MONGO_URL = os.environ.get('MONGO_URL', 'mongodb://localhost:27017')
client = AsyncIOMotorClient(MONGO_URL)
db = client['innovate_books_db']


async def seed_extended_customers():
    """Seed 20 customers"""
    print("📝 Seeding 20 Customers...")
    
    customers = [
        {
            "id": "CUST-0001",
            "customer_code": "CUST001",
            "customer_name": "Tata Motors Limited",
            "industry": "Automotive",
            "region": "West",
            "country": "India",
            "credit_rating": "A",
            "credit_limit": 50000000.0,
            "outstanding_amount": 10000000.0,
            "gstin": "27AAACT2727Q1ZW",
            "pan": "AAACT2727Q",
            "contact_person": "Rajesh Kumar",
            "contact_email": "rajesh.kumar@tatamotors.com",
            "contact_phone": "+91-22-6665-8282",
            "payment_terms": "Net 45",
            "is_active": True,
            "blacklisted": False,
            "created_at": datetime.utcnow().isoformat()
        },
        {
            "id": "CUST-0002",
            "customer_code": "CUST002",
            "customer_name": "Mahindra & Mahindra",
            "industry": "Automotive",
            "region": "West",
            "country": "India",
            "credit_rating": "A",
            "credit_limit": 40000000.0,
            "outstanding_amount": 5000000.0,
            "gstin": "27AAACM3266M1ZL",
            "pan": "AAACM3266M",
            "contact_person": "Priya Sharma",
            "contact_email": "priya.sharma@mahindra.com",
            "contact_phone": "+91-22-2491-5000",
            "payment_terms": "Net 30",
            "is_active": True,
            "blacklisted": False,
            "created_at": datetime.utcnow().isoformat()
        },
        {
            "id": "CUST-0003",
            "customer_code": "CUST003",
            "customer_name": "Bharat Forge Limited",
            "industry": "Metals & Forging",
            "region": "West",
            "country": "India",
            "credit_rating": "A+",
            "credit_limit": 60000000.0,
            "outstanding_amount": 8000000.0,
            "gstin": "27AAACB4073A1ZM",
            "pan": "AAACB4073A",
            "contact_person": "Sunil Desai",
            "contact_email": "sunil.desai@bharatforge.com",
            "contact_phone": "+91-20-6628-3000",
            "payment_terms": "Net 60",
            "is_active": True,
            "blacklisted": False,
            "created_at": datetime.utcnow().isoformat()
        },
        {
            "id": "CUST-0004",
            "customer_code": "CUST004",
            "customer_name": "Larsen & Toubro Limited",
            "industry": "Heavy Engineering",
            "region": "South",
            "country": "India",
            "credit_rating": "A+",
            "credit_limit": 100000000.0,
            "outstanding_amount": 20000000.0,
            "gstin": "33AAACL0230B1ZS",
            "pan": "AAACL0230B",
            "contact_person": "Arun Menon",
            "contact_email": "arun.menon@larsentoubro.com",
            "contact_phone": "+91-44-2854-5151",
            "payment_terms": "Net 90",
            "is_active": True,
            "blacklisted": False,
            "created_at": datetime.utcnow().isoformat()
        },
        {
            "id": "CUST-0005",
            "customer_code": "CUST005",
            "customer_name": "Hindustan Aeronautics Limited",
            "industry": "Aerospace",
            "region": "South",
            "country": "India",
            "credit_rating": "A",
            "credit_limit": 75000000.0,
            "outstanding_amount": 12000000.0,
            "gstin": "29AAACH1158J1Z4",
            "pan": "AAACH1158J",
            "contact_person": "Vikram Rao",
            "contact_email": "vikram.rao@hal-india.co.in",
            "contact_phone": "+91-80-2252-0001",
            "payment_terms": "Net 60",
            "is_active": True,
            "blacklisted": False,
            "created_at": datetime.utcnow().isoformat()
        },
        {
            "id": "CUST-0006",
            "customer_code": "CUST006",
            "customer_name": "Ashok Leyland Limited",
            "industry": "Automotive",
            "region": "South",
            "country": "India",
            "credit_rating": "A",
            "credit_limit": 35000000.0,
            "outstanding_amount": 7000000.0,
            "gstin": "33AAACA3834R1ZY",
            "pan": "AAACA3834R",
            "contact_person": "Ramesh Iyer",
            "contact_email": "ramesh.iyer@ashokleyland.com",
            "contact_phone": "+91-44-4299-4000",
            "payment_terms": "Net 45",
            "is_active": True,
            "blacklisted": False,
            "created_at": datetime.utcnow().isoformat()
        },
        {
            "id": "CUST-0007",
            "customer_code": "CUST007",
            "customer_name": "Maruti Suzuki India Limited",
            "industry": "Automotive",
            "region": "North",
            "country": "India",
            "credit_rating": "A+",
            "credit_limit": 80000000.0,
            "outstanding_amount": 15000000.0,
            "gstin": "07AAACM5988L1ZN",
            "pan": "AAACM5988L",
            "contact_person": "Ankit Verma",
            "contact_email": "ankit.verma@maruti.co.in",
            "contact_phone": "+91-124-435-2000",
            "payment_terms": "Net 30",
            "is_active": True,
            "blacklisted": False,
            "created_at": datetime.utcnow().isoformat()
        },
        {
            "id": "CUST-0008",
            "customer_code": "CUST008",
            "customer_name": "Hero MotoCorp Limited",
            "industry": "Automotive",
            "region": "North",
            "country": "India",
            "credit_rating": "A",
            "credit_limit": 45000000.0,
            "outstanding_amount": 9000000.0,
            "gstin": "06AAACH3359F1ZV",
            "pan": "AAACH3359F",
            "contact_person": "Neha Gupta",
            "contact_email": "neha.gupta@heromotocorp.com",
            "contact_phone": "+91-124-234-0100",
            "payment_terms": "Net 45",
            "is_active": True,
            "blacklisted": False,
            "created_at": datetime.utcnow().isoformat()
        },
        {
            "id": "CUST-0009",
            "customer_code": "CUST009",
            "customer_name": "Bajaj Auto Limited",
            "industry": "Automotive",
            "region": "West",
            "country": "India",
            "credit_rating": "A",
            "credit_limit": 42000000.0,
            "outstanding_amount": 8500000.0,
            "gstin": "27AAACB0950N1ZF",
            "pan": "AAACB0950N",
            "contact_person": "Sanjay Patil",
            "contact_email": "sanjay.patil@bajajauto.com",
            "contact_phone": "+91-20-2721-0300",
            "payment_terms": "Net 45",
            "is_active": True,
            "blacklisted": False,
            "created_at": datetime.utcnow().isoformat()
        },
        {
            "id": "CUST-0010",
            "customer_code": "CUST010",
            "customer_name": "Godrej & Boyce Mfg. Co. Ltd",
            "industry": "Industrial Machinery",
            "region": "West",
            "country": "India",
            "credit_rating": "A",
            "credit_limit": 38000000.0,
            "outstanding_amount": 6000000.0,
            "gstin": "27AAACG0569C1ZD",
            "pan": "AAACG0569C",
            "contact_person": "Meera Joshi",
            "contact_email": "meera.joshi@godrej.com",
            "contact_phone": "+91-22-2518-8010",
            "payment_terms": "Net 60",
            "is_active": True,
            "blacklisted": False,
            "created_at": datetime.utcnow().isoformat()
        },
        {
            "id": "CUST-0011",
            "customer_code": "CUST011",
            "customer_name": "Cummins India Limited",
            "industry": "Industrial Machinery",
            "region": "West",
            "country": "India",
            "credit_rating": "A+",
            "credit_limit": 55000000.0,
            "outstanding_amount": 11000000.0,
            "gstin": "27AAACC2095A1Z3",
            "pan": "AAACC2095A",
            "contact_person": "Rohit Khanna",
            "contact_email": "rohit.khanna@cummins.com",
            "contact_phone": "+91-20-6694-1000",
            "payment_terms": "Net 45",
            "is_active": True,
            "blacklisted": False,
            "created_at": datetime.utcnow().isoformat()
        },
        {
            "id": "CUST-0012",
            "customer_code": "CUST012",
            "customer_name": "Bosch Limited",
            "industry": "Automotive",
            "region": "South",
            "country": "India",
            "credit_rating": "A+",
            "credit_limit": 70000000.0,
            "outstanding_amount": 14000000.0,
            "gstin": "29AAACB7052A1ZO",
            "pan": "AAACB7052A",
            "contact_person": "Kavita Nair",
            "contact_email": "kavita.nair@in.bosch.com",
            "contact_phone": "+91-80-6754-0000",
            "payment_terms": "Net 30",
            "is_active": True,
            "blacklisted": False,
            "created_at": datetime.utcnow().isoformat()
        },
        {
            "id": "CUST-0013",
            "customer_code": "CUST013",
            "customer_name": "ABB India Limited",
            "industry": "Electronics & Electrical",
            "region": "South",
            "country": "India",
            "credit_rating": "A",
            "credit_limit": 48000000.0,
            "outstanding_amount": 9500000.0,
            "gstin": "29AAACA0169E1ZX",
            "pan": "AAACA0169E",
            "contact_person": "Deepak Singh",
            "contact_email": "deepak.singh@in.abb.com",
            "contact_phone": "+91-80-2294-9150",
            "payment_terms": "Net 45",
            "is_active": True,
            "blacklisted": False,
            "created_at": datetime.utcnow().isoformat()
        },
        {
            "id": "CUST-0014",
            "customer_code": "CUST014",
            "customer_name": "Siemens Limited",
            "industry": "Electronics & Electrical",
            "region": "West",
            "country": "India",
            "credit_rating": "A+",
            "credit_limit": 65000000.0,
            "outstanding_amount": 13000000.0,
            "gstin": "27AAACS3831L1ZK",
            "pan": "AAACS3831L",
            "contact_person": "Pooja Reddy",
            "contact_email": "pooja.reddy@siemens.com",
            "contact_phone": "+91-22-3967-7000",
            "payment_terms": "Net 30",
            "is_active": True,
            "blacklisted": False,
            "created_at": datetime.utcnow().isoformat()
        },
        {
            "id": "CUST-0015",
            "customer_code": "CUST015",
            "customer_name": "Thermax Limited",
            "industry": "Industrial Machinery",
            "region": "West",
            "country": "India",
            "credit_rating": "A",
            "credit_limit": 40000000.0,
            "outstanding_amount": 8000000.0,
            "gstin": "27AAACT1156P1ZG",
            "pan": "AAACT1156P",
            "contact_person": "Amit Kulkarni",
            "contact_email": "amit.kulkarni@thermaxglobal.com",
            "contact_phone": "+91-20-6627-4000",
            "payment_terms": "Net 60",
            "is_active": True,
            "blacklisted": False,
            "created_at": datetime.utcnow().isoformat()
        },
        {
            "id": "CUST-0016",
            "customer_code": "CUST016",
            "customer_name": "Voltas Limited",
            "industry": "Industrial Machinery",
            "region": "West",
            "country": "India",
            "credit_rating": "A",
            "credit_limit": 36000000.0,
            "outstanding_amount": 7200000.0,
            "gstin": "27AAACV4670G1ZT",
            "pan": "AAACV4670G",
            "contact_person": "Rajiv Malhotra",
            "contact_email": "rajiv.malhotra@voltas.com",
            "contact_phone": "+91-22-6665-6000",
            "payment_terms": "Net 45",
            "is_active": True,
            "blacklisted": False,
            "created_at": datetime.utcnow().isoformat()
        },
        {
            "id": "CUST-0017",
            "customer_code": "CUST017",
            "customer_name": "Blue Star Limited",
            "industry": "Industrial Machinery",
            "region": "West",
            "country": "India",
            "credit_rating": "A",
            "credit_limit": 32000000.0,
            "outstanding_amount": 6400000.0,
            "gstin": "27AAACB2151M1Z8",
            "pan": "AAACB2151M",
            "contact_person": "Sunita Rao",
            "contact_email": "sunita.rao@bluestarindia.com",
            "contact_phone": "+91-22-6665-4000",
            "payment_terms": "Net 45",
            "is_active": True,
            "blacklisted": False,
            "created_at": datetime.utcnow().isoformat()
        },
        {
            "id": "CUST-0018",
            "customer_code": "CUST018",
            "customer_name": "Crompton Greaves Consumer Electricals",
            "industry": "Electronics & Electrical",
            "region": "West",
            "country": "India",
            "credit_rating": "B+",
            "credit_limit": 28000000.0,
            "outstanding_amount": 5600000.0,
            "gstin": "27AAACC6703G1Z1",
            "pan": "AAACC6703G",
            "contact_person": "Manoj Agarwal",
            "contact_email": "manoj.agarwal@crompton.co.in",
            "contact_phone": "+91-22-2826-5555",
            "payment_terms": "Net 30",
            "is_active": True,
            "blacklisted": False,
            "created_at": datetime.utcnow().isoformat()
        },
        {
            "id": "CUST-0019",
            "customer_code": "CUST019",
            "customer_name": "Havells India Limited",
            "industry": "Electronics & Electrical",
            "region": "North",
            "country": "India",
            "credit_rating": "A",
            "credit_limit": 44000000.0,
            "outstanding_amount": 8800000.0,
            "gstin": "07AAACH0144C1ZW",
            "pan": "AAACH0144C",
            "contact_person": "Pradeep Bansal",
            "contact_email": "pradeep.bansal@havells.com",
            "contact_phone": "+91-120-3331-000",
            "payment_terms": "Net 45",
            "is_active": True,
            "blacklisted": False,
            "created_at": datetime.utcnow().isoformat()
        },
        {
            "id": "CUST-0020",
            "customer_code": "CUST020",
            "customer_name": "Polycab India Limited",
            "industry": "Electronics & Electrical",
            "region": "West",
            "country": "India",
            "credit_rating": "A",
            "credit_limit": 39000000.0,
            "outstanding_amount": 7800000.0,
            "gstin": "27AAACP5971J1ZH",
            "pan": "AAACP5971J",
            "contact_person": "Nilesh Desai",
            "contact_email": "nilesh.desai@polycab.com",
            "contact_phone": "+91-22-3075-9000",
            "payment_terms": "Net 45",
            "is_active": True,
            "blacklisted": False,
            "created_at": datetime.utcnow().isoformat()
        }
    ]
    
    await db['mfg_customers'].delete_many({})
    await db['mfg_customers'].insert_many(customers)
    print(f"✅ Inserted {len(customers)} customers")
    return len(customers)


async def seed_extended_leads():
    """Seed 15 manufacturing leads"""
    print("📝 Seeding 15 Manufacturing Leads...")
    
    leads = [
        {
            "lead_id": "MFGL-2025-0001",
            "customer_id": "CUST-0001",
            "customer_name": "Tata Motors Limited",
            "customer_industry": "Automotive",
            "contact_name": "Rajesh Kumar",
            "contact_email": "rajesh.kumar@tatamotors.com",
            "contact_phone": "+91-22-6665-8282",
            "product_description": "Aluminum Cylinder Head for BS6 Engine - High precision casting with 16 valve seats",
            "quantity": 5000,
            "uom": "PC",
            "delivery_date_required": (datetime.utcnow() + timedelta(days=120)).isoformat(),
            "priority": "High",
            "current_stage": "Feasibility",
            "status": "Active",
            "assigned_to_name": "Ravi Sharma",
            "assigned_to_role": "Sales Representative",
            "created_at": datetime.utcnow().isoformat(),
            "risk_level": "Medium",
            "risk_score": 45
        },
        {
            "lead_id": "MFGL-2025-0002",
            "customer_id": "CUST-0002",
            "customer_name": "Mahindra & Mahindra",
            "customer_industry": "Automotive",
            "contact_name": "Priya Sharma",
            "contact_email": "priya.sharma@mahindra.com",
            "contact_phone": "+91-22-2491-5000",
            "product_description": "Forged Steel Crankshaft for SUV Application - 4-cylinder inline configuration",
            "quantity": 3000,
            "uom": "PC",
            "delivery_date_required": (datetime.utcnow() + timedelta(days=90)).isoformat(),
            "priority": "High",
            "current_stage": "Costing",
            "status": "Active",
            "assigned_to_name": "Anjali Mehta",
            "assigned_to_role": "Sales Representative",
            "created_at": datetime.utcnow().isoformat(),
            "risk_level": "Low",
            "risk_score": 25
        },
        {
            "lead_id": "MFGL-2025-0003",
            "customer_id": "CUST-0003",
            "customer_name": "Bharat Forge Limited",
            "customer_industry": "Metals & Forging",
            "contact_name": "Sunil Desai",
            "contact_email": "sunil.desai@bharatforge.com",
            "contact_phone": "+91-20-6628-3000",
            "product_description": "High-strength Front Suspension Arm - Grade 8.8 alloy steel",
            "quantity": 10000,
            "uom": "PC",
            "delivery_date_required": (datetime.utcnow() + timedelta(days=150)).isoformat(),
            "priority": "Medium",
            "current_stage": "Approval",
            "status": "Active",
            "assigned_to_name": "Karthik Iyer",
            "assigned_to_role": "Sales Representative",
            "created_at": datetime.utcnow().isoformat(),
            "risk_level": "Low",
            "risk_score": 20
        },
        {
            "lead_id": "MFGL-2025-0004",
            "customer_id": "CUST-0004",
            "customer_name": "Larsen & Toubro Limited",
            "customer_industry": "Heavy Engineering",
            "contact_name": "Arun Menon",
            "contact_email": "arun.menon@larsentoubro.com",
            "contact_phone": "+91-44-2854-5151",
            "product_description": "Heavy Duty Gearbox Housing - Cast Iron FG300 with CNC machining",
            "quantity": 500,
            "uom": "PC",
            "delivery_date_required": (datetime.utcnow() + timedelta(days=180)).isoformat(),
            "priority": "High",
            "current_stage": "Feasibility",
            "status": "Active",
            "assigned_to_name": "Ravi Sharma",
            "assigned_to_role": "Sales Representative",
            "created_at": datetime.utcnow().isoformat(),
            "risk_level": "Medium",
            "risk_score": 50
        },
        {
            "lead_id": "MFGL-2025-0005",
            "customer_id": "CUST-0005",
            "customer_name": "Hindustan Aeronautics Limited",
            "customer_industry": "Aerospace",
            "contact_name": "Vikram Rao",
            "contact_email": "vikram.rao@hal-india.co.in",
            "contact_phone": "+91-80-2252-0001",
            "product_description": "Titanium Alloy Turbine Blade - Ti-6Al-4V with precision investment casting",
            "quantity": 1000,
            "uom": "PC",
            "delivery_date_required": (datetime.utcnow() + timedelta(days=240)).isoformat(),
            "priority": "Critical",
            "current_stage": "Intake",
            "status": "New",
            "assigned_to_name": "Deepa Nair",
            "assigned_to_role": "Sales Representative",
            "created_at": datetime.utcnow().isoformat(),
            "risk_level": "High",
            "risk_score": 75
        },
        {
            "lead_id": "MFGL-2025-0006",
            "customer_id": "CUST-0006",
            "customer_name": "Ashok Leyland Limited",
            "customer_industry": "Automotive",
            "contact_name": "Ramesh Iyer",
            "contact_email": "ramesh.iyer@ashokleyland.com",
            "contact_phone": "+91-44-4299-4000",
            "product_description": "Commercial Vehicle Brake Drum - Ductile iron grade 65-45-12",
            "quantity": 8000,
            "uom": "PC",
            "delivery_date_required": (datetime.utcnow() + timedelta(days=100)).isoformat(),
            "priority": "High",
            "current_stage": "Costing",
            "status": "Active",
            "assigned_to_name": "Anjali Mehta",
            "assigned_to_role": "Sales Representative",
            "created_at": datetime.utcnow().isoformat(),
            "risk_level": "Low",
            "risk_score": 30
        },
        {
            "lead_id": "MFGL-2025-0007",
            "customer_id": "CUST-0007",
            "customer_name": "Maruti Suzuki India Limited",
            "customer_industry": "Automotive",
            "contact_name": "Ankit Verma",
            "contact_email": "ankit.verma@maruti.co.in",
            "contact_phone": "+91-124-435-2000",
            "product_description": "Transmission Gear Set - Carburized steel with grinding to IT6 tolerance",
            "quantity": 15000,
            "uom": "SET",
            "delivery_date_required": (datetime.utcnow() + timedelta(days=75)).isoformat(),
            "priority": "High",
            "current_stage": "Feasibility",
            "status": "Active",
            "assigned_to_name": "Karthik Iyer",
            "assigned_to_role": "Sales Representative",
            "created_at": datetime.utcnow().isoformat(),
            "risk_level": "Medium",
            "risk_score": 40
        },
        {
            "lead_id": "MFGL-2025-0008",
            "customer_id": "CUST-0008",
            "customer_name": "Hero MotoCorp Limited",
            "customer_industry": "Automotive",
            "contact_name": "Neha Gupta",
            "contact_email": "neha.gupta@heromotocorp.com",
            "contact_phone": "+91-124-234-0100",
            "product_description": "Motorcycle Engine Block - Die cast aluminum with sleeve inserts",
            "quantity": 20000,
            "uom": "PC",
            "delivery_date_required": (datetime.utcnow() + timedelta(days=110)).isoformat(),
            "priority": "High",
            "current_stage": "Approval",
            "status": "Active",
            "assigned_to_name": "Ravi Sharma",
            "assigned_to_role": "Sales Representative",
            "created_at": datetime.utcnow().isoformat(),
            "risk_level": "Low",
            "risk_score": 22
        },
        {
            "lead_id": "MFGL-2025-0009",
            "customer_id": "CUST-0009",
            "customer_name": "Bajaj Auto Limited",
            "customer_industry": "Automotive",
            "contact_name": "Sanjay Patil",
            "contact_email": "sanjay.patil@bajajauto.com",
            "contact_phone": "+91-20-2721-0300",
            "product_description": "Connecting Rod Assembly - Forged steel with precision machining",
            "quantity": 12000,
            "uom": "PC",
            "delivery_date_required": (datetime.utcnow() + timedelta(days=95)).isoformat(),
            "priority": "Medium",
            "current_stage": "Costing",
            "status": "Active",
            "assigned_to_name": "Anjali Mehta",
            "assigned_to_role": "Sales Representative",
            "created_at": datetime.utcnow().isoformat(),
            "risk_level": "Low",
            "risk_score": 28
        },
        {
            "lead_id": "MFGL-2025-0010",
            "customer_id": "CUST-0010",
            "customer_name": "Godrej & Boyce Mfg. Co. Ltd",
            "customer_industry": "Industrial Machinery",
            "contact_name": "Meera Joshi",
            "contact_email": "meera.joshi@godrej.com",
            "contact_phone": "+91-22-2518-8010",
            "product_description": "Industrial Lock Mechanism Housing - Zinc die casting with electroplating",
            "quantity": 50000,
            "uom": "PC",
            "delivery_date_required": (datetime.utcnow() + timedelta(days=60)).isoformat(),
            "priority": "Medium",
            "current_stage": "Feasibility",
            "status": "Active",
            "assigned_to_name": "Deepa Nair",
            "assigned_to_role": "Sales Representative",
            "created_at": datetime.utcnow().isoformat(),
            "risk_level": "Low",
            "risk_score": 18
        },
        {
            "lead_id": "MFGL-2025-0011",
            "customer_id": "CUST-0011",
            "customer_name": "Cummins India Limited",
            "customer_industry": "Industrial Machinery",
            "contact_name": "Rohit Khanna",
            "contact_email": "rohit.khanna@cummins.com",
            "contact_phone": "+91-20-6694-1000",
            "product_description": "Diesel Engine Cylinder Head - High-grade cast iron with multi-valve design",
            "quantity": 4000,
            "uom": "PC",
            "delivery_date_required": (datetime.utcnow() + timedelta(days=130)).isoformat(),
            "priority": "High",
            "current_stage": "Intake",
            "status": "New",
            "assigned_to_name": "Karthik Iyer",
            "assigned_to_role": "Sales Representative",
            "created_at": datetime.utcnow().isoformat(),
            "risk_level": "Medium",
            "risk_score": 42
        },
        {
            "lead_id": "MFGL-2025-0012",
            "customer_id": "CUST-0012",
            "customer_name": "Bosch Limited",
            "customer_industry": "Automotive",
            "contact_name": "Kavita Nair",
            "contact_email": "kavita.nair@in.bosch.com",
            "contact_phone": "+91-80-6754-0000",
            "product_description": "Fuel Injection Pump Body - Aluminum alloy with precision boring",
            "quantity": 6000,
            "uom": "PC",
            "delivery_date_required": (datetime.utcnow() + timedelta(days=105)).isoformat(),
            "priority": "High",
            "current_stage": "Costing",
            "status": "Active",
            "assigned_to_name": "Ravi Sharma",
            "assigned_to_role": "Sales Representative",
            "created_at": datetime.utcnow().isoformat(),
            "risk_level": "Low",
            "risk_score": 26
        },
        {
            "lead_id": "MFGL-2025-0013",
            "customer_id": "CUST-0013",
            "customer_name": "ABB India Limited",
            "customer_industry": "Electronics & Electrical",
            "contact_name": "Deepak Singh",
            "contact_email": "deepak.singh@in.abb.com",
            "contact_phone": "+91-80-2294-9150",
            "product_description": "Electric Motor Housing - Aluminum die casting with powder coating",
            "quantity": 7500,
            "uom": "PC",
            "delivery_date_required": (datetime.utcnow() + timedelta(days=115)).isoformat(),
            "priority": "Medium",
            "current_stage": "Feasibility",
            "status": "Active",
            "assigned_to_name": "Anjali Mehta",
            "assigned_to_role": "Sales Representative",
            "created_at": datetime.utcnow().isoformat(),
            "risk_level": "Low",
            "risk_score": 24
        },
        {
            "lead_id": "MFGL-2025-0014",
            "customer_id": "CUST-0014",
            "customer_name": "Siemens Limited",
            "customer_industry": "Electronics & Electrical",
            "contact_name": "Pooja Reddy",
            "contact_email": "pooja.reddy@siemens.com",
            "contact_phone": "+91-22-3967-7000",
            "product_description": "Circuit Breaker Contact Assembly - Copper alloy with silver plating",
            "quantity": 25000,
            "uom": "PC",
            "delivery_date_required": (datetime.utcnow() + timedelta(days=85)).isoformat(),
            "priority": "High",
            "current_stage": "Approval",
            "status": "Active",
            "assigned_to_name": "Deepa Nair",
            "assigned_to_role": "Sales Representative",
            "created_at": datetime.utcnow().isoformat(),
            "risk_level": "Low",
            "risk_score": 20
        },
        {
            "lead_id": "MFGL-2025-0015",
            "customer_id": "CUST-0015",
            "customer_name": "Thermax Limited",
            "customer_industry": "Industrial Machinery",
            "contact_name": "Amit Kulkarni",
            "contact_email": "amit.kulkarni@thermaxglobal.com",
            "contact_phone": "+91-20-6627-4000",
            "product_description": "Boiler Tube Manifold - High-grade steel with seamless welding",
            "quantity": 300,
            "uom": "PC",
            "delivery_date_required": (datetime.utcnow() + timedelta(days=200)).isoformat(),
            "priority": "Medium",
            "current_stage": "Intake",
            "status": "New",
            "assigned_to_name": "Karthik Iyer",
            "assigned_to_role": "Sales Representative",
            "created_at": datetime.utcnow().isoformat(),
            "risk_level": "Medium",
            "risk_score": 48
        }
    ]
    
    await db['mfg_leads'].delete_many({})
    await db['mfg_leads'].insert_many(leads)
    print(f"✅ Inserted {len(leads)} manufacturing leads")
    return len(leads)


async def main():
    print("=" * 70)
    print("EXTENDED SEED DATA FOR MANUFACTURING LEAD MODULE")
    print("=" * 70)
    
    customer_count = await seed_extended_customers()
    lead_count = await seed_extended_leads()
    
    print("\n" + "=" * 70)
    print("EXTENDED SEED DATA SUMMARY")
    print("=" * 70)
    print(f"   - Customers: {customer_count}")
    print(f"   - Manufacturing Leads: {lead_count}")
    print("=" * 70)
    print("✅ Extended seed data completed successfully!")
    print("=" * 70)


if __name__ == "__main__":
    asyncio.run(main())
