"""
Finance PDF Export Routes
Generate PDF reports for Financial Statements
"""

from fastapi import APIRouter, HTTPException, Depends, Header
from fastapi.responses import StreamingResponse
from datetime import datetime, timezone
import jwt
import os
import io

router = APIRouter(prefix="/api/ib-finance/export", tags=["Finance Export"])

JWT_SECRET = os.environ["JWT_SECRET_KEY"]  # must be set in backend/.env


def get_db():
    from server import db
    return db


async def get_current_user(authorization: str = Header(None)):
    if not authorization:
        raise HTTPException(status_code=401, detail="Not authenticated")
    
    try:
        token = authorization.replace("Bearer ", "")
        payload = jwt.decode(token, JWT_SECRET, algorithms=["HS256"])
        return {
            "user_id": payload.get("user_id"),
            "org_id": payload.get("org_id")
        }
    except:
        raise HTTPException(status_code=401, detail="Invalid token")


def generate_html_statement(title: str, period: str, content: str, org_name: str = "InnovateBooks"):
    """Generate HTML template for PDF conversion"""
    return f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <title>{title}</title>
        <style>
            body {{ font-family: 'Segoe UI', Arial, sans-serif; margin: 40px; color: #1a1a1a; }}
            .header {{ border-bottom: 3px solid #3A4E63; padding-bottom: 20px; margin-bottom: 30px; }}
            .header h1 {{ color: #3A4E63; margin: 0; font-size: 24px; }}
            .header .period {{ color: #666; font-size: 14px; margin-top: 5px; }}
            .header .org {{ color: #333; font-size: 16px; font-weight: bold; margin-top: 10px; }}
            table {{ width: 100%; border-collapse: collapse; margin: 20px 0; }}
            th {{ background: #f5f5f5; text-align: left; padding: 12px; font-weight: 600; border-bottom: 2px solid #ddd; }}
            td {{ padding: 10px 12px; border-bottom: 1px solid #eee; }}
            .section-header {{ background: #3A4E63; color: white; padding: 10px 12px; font-weight: 600; margin-top: 20px; }}
            .total-row {{ background: #f0f4f8; font-weight: bold; }}
            .total-row td {{ border-top: 2px solid #3A4E63; }}
            .amount {{ text-align: right; font-family: 'Courier New', monospace; }}
            .positive {{ color: #059669; }}
            .negative {{ color: #dc2626; }}
            .grand-total {{ background: #3A4E63; color: white; }}
            .grand-total td {{ font-size: 18px; padding: 15px 12px; }}
            .footer {{ margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 12px; color: #666; }}
            .generated {{ float: right; }}
        </style>
    </head>
    <body>
        <div class="header">
            <h1>{title}</h1>
            <div class="org">{org_name}</div>
            <div class="period">For the period ending: {period}</div>
        </div>
        {content}
        <div class="footer">
            <span>Generated by IB Finance</span>
            <span class="generated">Generated on: {datetime.now().strftime('%d %b %Y, %H:%M')}</span>
        </div>
    </body>
    </html>
    """


def format_currency(amount: float) -> str:
    """Format amount as Indian currency"""
    if amount < 0:
        return f"(₹{abs(amount):,.0f})"
    return f"₹{amount:,.0f}"


@router.get("/profit-loss/{period}")
async def export_profit_loss_pdf(period: str, current_user: dict = Depends(get_current_user)):
    """Export Profit & Loss statement as HTML (for PDF conversion)"""
    db = get_db()
    org_id = current_user.get("org_id")
    
    # Get P&L data (reuse logic from ib_finance_routes)
    # Get billing for revenue
    billing_pipeline = [
        {"$match": {"org_id": org_id, "status": "issued"}},
        {"$group": {"_id": None, "total_revenue": {"$sum": "$gross_amount"}}}
    ]
    billing_result = await db.fin_billing_records.aggregate(billing_pipeline).to_list(length=1)
    total_revenue = billing_result[0].get("total_revenue", 0) if billing_result else 0
    
    # Get depreciation as expense
    dep_total = await db.fin_depreciation_schedules.aggregate([
        {"$match": {"org_id": org_id}},
        {"$group": {"_id": None, "total": {"$sum": "$depreciation_amount"}}}
    ]).to_list(length=1)
    depreciation = dep_total[0].get("total", 0) if dep_total else 0
    
    net_income = total_revenue - depreciation
    
    content = f"""
    <table>
        <tr class="section-header"><td colspan="2">Revenue</td></tr>
        <tr>
            <td>Revenue - Services</td>
            <td class="amount positive">{format_currency(total_revenue)}</td>
        </tr>
        <tr class="total-row">
            <td>Total Revenue</td>
            <td class="amount positive">{format_currency(total_revenue)}</td>
        </tr>
        
        <tr class="section-header"><td colspan="2">Expenses</td></tr>
        <tr>
            <td>Depreciation Expense</td>
            <td class="amount negative">{format_currency(depreciation)}</td>
        </tr>
        <tr class="total-row">
            <td>Total Expenses</td>
            <td class="amount negative">{format_currency(depreciation)}</td>
        </tr>
        
        <tr class="grand-total">
            <td>Net Income</td>
            <td class="amount {'positive' if net_income >= 0 else 'negative'}">{format_currency(net_income)}</td>
        </tr>
    </table>
    """
    
    html = generate_html_statement("Profit & Loss Statement", period, content)
    
    return StreamingResponse(
        io.BytesIO(html.encode()),
        media_type="text/html",
        headers={"Content-Disposition": f"attachment; filename=PnL_{period}.html"}
    )


@router.get("/balance-sheet/{period}")
async def export_balance_sheet_pdf(period: str, current_user: dict = Depends(get_current_user)):
    """Export Balance Sheet as HTML"""
    db = get_db()
    org_id = current_user.get("org_id")
    
    # Get receivables
    rcv_total = await db.fin_receivables.aggregate([
        {"$match": {"org_id": org_id}},
        {"$group": {"_id": None, "total": {"$sum": "$outstanding_amount"}}}
    ]).to_list(length=1)
    receivables = rcv_total[0].get("total", 0) if rcv_total else 0
    
    # Get assets
    asset_total = await db.fin_assets.aggregate([
        {"$match": {"org_id": org_id, "status": "active"}},
        {"$group": {
            "_id": None, 
            "cap_value": {"$sum": "$capitalization_value"},
            "acc_dep": {"$sum": "$accumulated_depreciation"}
        }}
    ]).to_list(length=1)
    fixed_assets = asset_total[0].get("cap_value", 0) if asset_total else 0
    acc_depreciation = asset_total[0].get("acc_dep", 0) if asset_total else 0
    
    # Get payables
    pay_total = await db.fin_payables.aggregate([
        {"$match": {"org_id": org_id, "status": {"$in": ["open", "partially_paid", "overdue"]}}},
        {"$group": {"_id": None, "total": {"$sum": "$outstanding_amount"}}}
    ]).to_list(length=1)
    payables = pay_total[0].get("total", 0) if pay_total else 0
    
    total_current_assets = receivables
    total_non_current_assets = fixed_assets - acc_depreciation
    total_assets = total_current_assets + total_non_current_assets
    total_liabilities = payables
    equity = total_assets - total_liabilities
    
    content = f"""
    <table>
        <tr class="section-header"><td colspan="2">Assets</td></tr>
        <tr><td colspan="2" style="background:#f9f9f9;font-weight:600;padding:8px 12px;">Current Assets</td></tr>
        <tr>
            <td>Accounts Receivable</td>
            <td class="amount">{format_currency(receivables)}</td>
        </tr>
        <tr class="total-row">
            <td>Total Current Assets</td>
            <td class="amount">{format_currency(total_current_assets)}</td>
        </tr>
        
        <tr><td colspan="2" style="background:#f9f9f9;font-weight:600;padding:8px 12px;">Non-Current Assets</td></tr>
        <tr>
            <td>Fixed Assets</td>
            <td class="amount">{format_currency(fixed_assets)}</td>
        </tr>
        <tr>
            <td>Less: Accumulated Depreciation</td>
            <td class="amount negative">{format_currency(-acc_depreciation)}</td>
        </tr>
        <tr class="total-row">
            <td>Total Non-Current Assets</td>
            <td class="amount">{format_currency(total_non_current_assets)}</td>
        </tr>
        
        <tr class="grand-total">
            <td>Total Assets</td>
            <td class="amount">{format_currency(total_assets)}</td>
        </tr>
    </table>
    
    <table style="margin-top:30px;">
        <tr class="section-header"><td colspan="2">Liabilities & Equity</td></tr>
        <tr><td colspan="2" style="background:#f9f9f9;font-weight:600;padding:8px 12px;">Current Liabilities</td></tr>
        <tr>
            <td>Accounts Payable</td>
            <td class="amount">{format_currency(payables)}</td>
        </tr>
        <tr class="total-row">
            <td>Total Liabilities</td>
            <td class="amount">{format_currency(total_liabilities)}</td>
        </tr>
        
        <tr><td colspan="2" style="background:#f9f9f9;font-weight:600;padding:8px 12px;">Equity</td></tr>
        <tr>
            <td>Retained Earnings</td>
            <td class="amount">{format_currency(equity)}</td>
        </tr>
        <tr class="total-row">
            <td>Total Equity</td>
            <td class="amount">{format_currency(equity)}</td>
        </tr>
        
        <tr class="grand-total">
            <td>Total Liabilities & Equity</td>
            <td class="amount">{format_currency(total_assets)}</td>
        </tr>
    </table>
    """
    
    html = generate_html_statement("Balance Sheet", period, content)
    
    return StreamingResponse(
        io.BytesIO(html.encode()),
        media_type="text/html",
        headers={"Content-Disposition": f"attachment; filename=BalanceSheet_{period}.html"}
    )


@router.get("/cash-flow/{period}")
async def export_cash_flow_pdf(period: str, current_user: dict = Depends(get_current_user)):
    """Export Cash Flow Statement as HTML"""
    db = get_db()
    org_id = current_user.get("org_id")
    
    # Get billing for net income
    billing_result = await db.fin_billing_records.aggregate([
        {"$match": {"org_id": org_id, "status": "issued"}},
        {"$group": {"_id": None, "total": {"$sum": "$gross_amount"}}}
    ]).to_list(length=1)
    net_income = billing_result[0].get("total", 0) if billing_result else 0
    
    # Get depreciation
    dep_total = await db.fin_depreciation_schedules.aggregate([
        {"$match": {"org_id": org_id}},
        {"$group": {"_id": None, "total": {"$sum": "$depreciation_amount"}}}
    ]).to_list(length=1)
    depreciation = dep_total[0].get("total", 0) if dep_total else 0
    
    # Get receivables change
    rcv_total = await db.fin_receivables.aggregate([
        {"$match": {"org_id": org_id}},
        {"$group": {"_id": None, "total": {"$sum": "$outstanding_amount"}}}
    ]).to_list(length=1)
    receivables_change = -(rcv_total[0].get("total", 0) if rcv_total else 0)
    
    # Get payables change
    pay_total = await db.fin_payables.aggregate([
        {"$match": {"org_id": org_id, "status": {"$in": ["open", "partially_paid", "overdue"]}}},
        {"$group": {"_id": None, "total": {"$sum": "$outstanding_amount"}}}
    ]).to_list(length=1)
    payables_change = pay_total[0].get("total", 0) if pay_total else 0
    
    # Get asset purchases
    asset_total = await db.fin_assets.aggregate([
        {"$match": {"org_id": org_id}},
        {"$group": {"_id": None, "total": {"$sum": "$capitalization_value"}}}
    ]).to_list(length=1)
    asset_purchases = -(asset_total[0].get("total", 0) if asset_total else 0)
    
    operating_cf = net_income + depreciation + receivables_change + payables_change
    investing_cf = asset_purchases
    financing_cf = 0
    net_change = operating_cf + investing_cf + financing_cf
    
    content = f"""
    <table>
        <tr class="section-header"><td colspan="2">Operating Activities</td></tr>
        <tr>
            <td>Net Income</td>
            <td class="amount">{format_currency(net_income)}</td>
        </tr>
        <tr>
            <td>Add: Depreciation & Amortization</td>
            <td class="amount">{format_currency(depreciation)}</td>
        </tr>
        <tr>
            <td>Change in Accounts Receivable</td>
            <td class="amount {'negative' if receivables_change < 0 else ''}">{format_currency(receivables_change)}</td>
        </tr>
        <tr>
            <td>Change in Accounts Payable</td>
            <td class="amount">{format_currency(payables_change)}</td>
        </tr>
        <tr class="total-row">
            <td>Net Cash from Operating Activities</td>
            <td class="amount {'positive' if operating_cf >= 0 else 'negative'}">{format_currency(operating_cf)}</td>
        </tr>
        
        <tr class="section-header"><td colspan="2">Investing Activities</td></tr>
        <tr>
            <td>Purchase of Fixed Assets</td>
            <td class="amount negative">{format_currency(asset_purchases)}</td>
        </tr>
        <tr class="total-row">
            <td>Net Cash from Investing Activities</td>
            <td class="amount {'positive' if investing_cf >= 0 else 'negative'}">{format_currency(investing_cf)}</td>
        </tr>
        
        <tr class="section-header"><td colspan="2">Financing Activities</td></tr>
        <tr>
            <td>Capital Contributions / (Distributions)</td>
            <td class="amount">{format_currency(financing_cf)}</td>
        </tr>
        <tr class="total-row">
            <td>Net Cash from Financing Activities</td>
            <td class="amount">{format_currency(financing_cf)}</td>
        </tr>
        
        <tr class="grand-total">
            <td>Net Change in Cash</td>
            <td class="amount {'positive' if net_change >= 0 else 'negative'}">{format_currency(net_change)}</td>
        </tr>
    </table>
    """
    
    html = generate_html_statement("Cash Flow Statement", period, content)
    
    return StreamingResponse(
        io.BytesIO(html.encode()),
        media_type="text/html",
        headers={"Content-Disposition": f"attachment; filename=CashFlow_{period}.html"}
    )


@router.get("/tax-summary/{period}")
async def export_tax_summary_pdf(period: str, current_user: dict = Depends(get_current_user)):
    """Export Tax Summary (GST/VAT) as HTML"""
    db = get_db()
    org_id = current_user.get("org_id")
    
    # Get output tax
    output_taxes = await db.fin_tax_transactions.aggregate([
        {"$match": {"org_id": org_id, "direction": "output", "filing_period": period}},
        {"$group": {
            "_id": "$tax_type",
            "taxable": {"$sum": "$taxable_amount"},
            "tax": {"$sum": "$tax_amount"},
            "count": {"$sum": 1}
        }}
    ]).to_list(length=100)
    
    # Get input tax
    input_taxes = await db.fin_tax_transactions.aggregate([
        {"$match": {"org_id": org_id, "direction": "input", "filing_period": period}},
        {"$group": {
            "_id": "$tax_type",
            "taxable": {"$sum": "$taxable_amount"},
            "tax": {"$sum": "$tax_amount"},
            "count": {"$sum": 1}
        }}
    ]).to_list(length=100)
    
    total_output = sum(t.get("tax", 0) for t in output_taxes)
    total_input = sum(t.get("tax", 0) for t in input_taxes)
    net_payable = total_output - total_input
    
    output_rows = ""
    for t in output_taxes:
        output_rows += f"""
        <tr>
            <td>{t.get('_id', 'Unknown')}</td>
            <td class="amount">{t.get('count', 0)}</td>
            <td class="amount">{format_currency(t.get('taxable', 0))}</td>
            <td class="amount">{format_currency(t.get('tax', 0))}</td>
        </tr>
        """
    
    input_rows = ""
    for t in input_taxes:
        input_rows += f"""
        <tr>
            <td>{t.get('_id', 'Unknown')}</td>
            <td class="amount">{t.get('count', 0)}</td>
            <td class="amount">{format_currency(t.get('taxable', 0))}</td>
            <td class="amount">{format_currency(t.get('tax', 0))}</td>
        </tr>
        """
    
    content = f"""
    <table>
        <tr class="section-header"><td colspan="4">Output Tax (Sales)</td></tr>
        <tr>
            <th>Tax Type</th>
            <th class="amount">Transactions</th>
            <th class="amount">Taxable Amount</th>
            <th class="amount">Tax Amount</th>
        </tr>
        {output_rows if output_rows else '<tr><td colspan="4" style="text-align:center;color:#666;">No output tax transactions</td></tr>'}
        <tr class="total-row">
            <td colspan="3">Total Output Tax</td>
            <td class="amount">{format_currency(total_output)}</td>
        </tr>
    </table>
    
    <table style="margin-top:30px;">
        <tr class="section-header"><td colspan="4">Input Tax Credit (Purchases)</td></tr>
        <tr>
            <th>Tax Type</th>
            <th class="amount">Transactions</th>
            <th class="amount">Taxable Amount</th>
            <th class="amount">Tax Amount</th>
        </tr>
        {input_rows if input_rows else '<tr><td colspan="4" style="text-align:center;color:#666;">No input tax transactions</td></tr>'}
        <tr class="total-row">
            <td colspan="3">Total Input Tax Credit</td>
            <td class="amount">{format_currency(total_input)}</td>
        </tr>
    </table>
    
    <table style="margin-top:30px;">
        <tr class="section-header"><td colspan="2">Tax Liability Summary</td></tr>
        <tr>
            <td>Output Tax (Payable)</td>
            <td class="amount">{format_currency(total_output)}</td>
        </tr>
        <tr>
            <td>Less: Input Tax Credit</td>
            <td class="amount negative">{format_currency(-total_input)}</td>
        </tr>
        <tr class="grand-total">
            <td>Net Tax {'Payable' if net_payable >= 0 else 'Refundable'}</td>
            <td class="amount {'positive' if net_payable >= 0 else 'negative'}">{format_currency(abs(net_payable))}</td>
        </tr>
    </table>
    """
    
    html = generate_html_statement("Tax Summary Report", period, content)
    
    return StreamingResponse(
        io.BytesIO(html.encode()),
        media_type="text/html",
        headers={"Content-Disposition": f"attachment; filename=TaxSummary_{period}.html"}
    )
